### ISSUE TITLE
Recherche d'utilisateur

### ISSUE THREAD

**Issue by Chnapy** [tommywalkie/taverne#2]
Lorsqu'on cherche un utilisateur, qu'on l'ajoute aux abonnements, et bah on le trouve encore dans le résultat des recherches.
L'idéal: l'enlever des résultats. Sinon au moins masquer le bouton d'ajout (et quand on clique dessus il faut le disable).

**Comment by tommywalkie** [comment]
Dans le dernier commit 17d8712175ec17fde7d3c7f28b59f9dda47da9c6 , le problème a été résolu de la manière suivante : Dorénavant lors de la recherche d'utilisateur, une liste de résultats apparaît, et si tel utilisateur fait déjà parti des abonnements, un bouton de désabonnement ("unfollow") apparaît, sinon c'est qu'il n'en fait pas parti, donc à la place, ce sera un bouton d'abonnement ("follow") qui apparaîtra.

De plus, si l'utilisateur courant souhaite se désabonner d'une personne depuis la liste des abonnements et non depuis la liste des résultats de la recherche, si cette personne était dans la liste des résultats d'une recherche, le bouton d'abonnement apparaît tandis que le bouton de désabonnement disparaîtra.

Voilà voilà. 👍
